#  #6


In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [ ]:
X.shape

(10, 2)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class myNN2(Dataset):
  def __init__(self,features,lables):
    super().__init__()
    self.features=features
    self.lables=lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx], self.lables[idx]

In [ ]:
dataset=myNN2(X,y)

In [ ]:
dataset[3]

(tensor([-0.7206, -0.9606]), tensor(0))

In [ ]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=1)

In [ ]:
for batch_features,batch_loaders in dataloader:
  print(batch_features)
  print(batch_loaders)
  print("-"*50)

tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------


In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
339     89812         M        23.51         24.27          155.10     1747.0   
527  91813702         B        12.34         12.27           78.94      468.5   
112     86409         B        14.26         19.65           97.83      629.9   
523    917896         B        13.71         18.68           88.73      571.0   
434    908469         B        14.86         16.94           94.89      673.7   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
339          0.10690           0.12830         0.23080              0.14100   
527          0.09003           0.06307         0.02958              0.02647   
112          0.07837           0.22330         0.30030              0.07798   
523          0.09916           0.10700         0.05385              0.03783   
434          0.08924           0.07074         0.03346              0.02877   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
339  ...          30.73           202.40      2906.0           0.15150   
527  ...          19.27            87.22       564.9           0.12920   
112  ...          23.73           107.00       709.0           0.08949   
523  ...          25.63            99.43       701.9           0.14250   
434  ...          20.54           102.30       777.5           0.12180   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
339             0.2678           0.4819               0.20890          0.2593   
527             0.2074           0.1791               0.10700          0.3110   
112             0.4193           0.6783               0.15050          0.2398   
523             0.2566           0.1935               0.12840          0.2849   
434             0.1550           0.1220               0.07971          0.2525   

     fractal_dimension_worst  Unnamed: 32  
339                  0.07738          NaN  
527                  0.07592          NaN  
112                  0.10820          NaN  
523                  0.09031          NaN  
434                  0.06827          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']

In [ ]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

y_train=LE.fit_transform(y_train)
y_test=LE.transform(y_test)

In [ ]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class for_ds(Dataset):
  def __init__(self,features,labels):
    super().__init__()
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [ ]:
train_ds=for_ds(X_train_tensor,y_train_tensor)
test_ds=for_ds(X_test_tensor,y_test_tensor)

In [ ]:
train_loader=DataLoader(train_ds,batch_size=32,shuffle=True)
test_loader=DataLoader(test_ds,batch_size=32,shuffle=True)

In [ ]:
import torch.nn as nn
import torch.optim as optim

In [ ]:
class myNN2(nn.Module):
  def __init__(self,l1_features):
    super().__init__()
    self.linear=nn.Sequential(
        nn.Linear(l1_features,1)
    )
    self.criterian=nn.BCEWithLogitsLoss()
    self.optimizer=optim.SGD(self.parameters(),lr=0.1)

  def forward(self,x):
    return self.linear(x)

  def loss(self,y_pred,y):
    return self.criterian(y_pred,y)

In [ ]:
apun=myNN2(X_train_tensor.shape[1])

In [ ]:
lr=0.1
epochs=10

for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:

    y_pred=apun(batch_features)
    loss=apun.loss(y_pred,batch_labels.view(-1,1))
    apun.optimizer.zero_grad()
    loss.backward()
    apun.optimizer.step()

  print(f"epoch: {epoch}   loss:{loss}")


epoch: 0   loss:0.22013525664806366
epoch: 1   loss:0.25239482522010803
epoch: 2   loss:0.2694806456565857
epoch: 3   loss:0.06471458822488785
epoch: 4   loss:0.1958785504102707
epoch: 5   loss:0.06049708276987076
epoch: 6   loss:0.0335206538438797
epoch: 7   loss:0.0789351835846901
epoch: 8   loss:0.12877455353736877
epoch: 9   loss:0.027936266735196114


In [ ]:
apun.eval()
accuracy=[]

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred=apun(batch_features)
    y_pred=(y_pred>0.8).float()
    accuracy.append((y_pred.view(-1)==batch_labels).float().mean().item())

overall_accuracy=sum(accuracy)/len(accuracy)
print(f"overall accuracy: {overall_accuracy}")

overall accuracy: 0.9644097238779068


#     #7

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split as tts

In [ ]:

torch.manual_seed(42)


In [ ]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"using device : {device}")


using device : cpu


In [ ]:
df=pd.read_csv("fashion-mnist_test.csv")
df.head()


FileNotFoundError: [Errno 2] No such file or directory: 'fashion-mnist_test.csv'

In [ ]:
X=df.drop(columns='label').values
y=df['label'].values
X=X/255.0
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)


In [ ]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)


In [ ]:
class myMNIST(Dataset):
  def __init__(self,features,labels):
    super().__init__()
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


In [ ]:
train_ds=myMNIST(X_train_tensor,y_train_tensor)
test_ds=myMNIST(X_test_tensor,y_test_tensor)


In [ ]:
# train_loader = DataLoader(train_ds,batch_size=128,shuffle=True)
# test_loader = DataLoader(test_ds,batch_size=128,shuffle=True)


In [ ]:
class MyNN3(nn.Module):
  def __init__(self,input_dim, output_dim,num_hidden_layer,neuron_per_layer,weight_decay,optim_name,lr):
    super().__init__()
    linear=[]

    for i in range(num_hidden_layer):
      if i==0:
        linear.append(nn.Linear(input_dim,neuron_per_layer))
      else: linear.append(nn.Linear(neuron_per_layer,neuron_per_layer))
      linear.append(nn.BatchNorm1d(neuron_per_layer))
      linear.append(nn.ReLU())
      linear.append(nn.Dropout(p=0.3))
    linear.append(nn.Linear(neuron_per_layer,output_dim))

    self.model=nn.Sequential(*linear)
    self.criterion = nn.CrossEntropyLoss()

    if(optim_name=="Adam"):
      self.optimizer = optim.Adam(self.parameters(),lr=lr,weight_decay=weight_decay)
    elif (optim_name=="SGD"):
      self.optimizer = optim.SGD(self.parameters(),lr=lr,weight_decay=weight_decay)
    elif (optim_name=="RMSprop"):
      self.optimizer = optim.RMSprop(self.parameters(),lr=lr,weight_decay=weight_decay)

  def forward(self,x):
    return self.model(x)

  def loss(self,y_pred,y):
    return self.criterion(y_pred,y)

In [ ]:
def objective(trial):
  num_hiden_layer=trial.suggest_int("num_hiden_layer",1,8)
  num_neuron_per_layer=trial.suggest_int("num_neuron_per_layer",8,128,step=8)
  epochs=trial.suggest_int("epochs",10,50,step=5)
  lr=trial.suggest_float("lr",1e-5,1e-1,log=True)
  dropout_rate=trial.suggest_float("dropoout_rate",0.1,0.5,step=0.1)
  batch_size=trial.suggest_categorical("batch_size",[32,64,128])
  optim_name=trial.suggest_categorical("optimizer",["SGD","Adam","RMSprop"])
  weight_decay=trial.suggest_float("weight_decay",1e-5,1e-1,log=True)


  train_loader = DataLoader(train_ds,batch_size=batch_size,shuffle=True)
  test_loader = DataLoader(test_ds,batch_size=batch_size,shuffle=True)

  input_dim=784
  output_dim=10

  model=MyNN3(input_dim,output_dim,num_hiden_layer,num_neuron_per_layer,weight_decay,optim_name,lr)
  model=model.to(device)

  for i in range(epochs):
    apun.train()
    for batch_feature,batch_label in train_loader:
      batch_feature = batch_feature.to(device)
      batch_label = batch_label.to(device)


      y_pred=apun(batch_feature)
      loss=apun.loss(y_pred,batch_label)

      apun.optimizer.zero_grad()
      loss.backward()
      apun.optimizer.step()

    apun.eval()
    accuracy=[]
    #this is for fashion mnist dataset and output has 10 classes.

    with torch.no_grad():
      for batch_feature,batch_label in test_loader:

        batch_feature = batch_feature.to(device, non_blocking=True)
        batch_label = batch_label.to(device, non_blocking=True)
        y_pred=apun.forward(batch_feature)
        y_pred=torch.argmax(y_pred,dim=1)
        accuracy.append((y_pred==batch_label).float().mean().item())

    overall_accuracy=sum(accuracy)/len(accuracy)
    return overall_accuracy

In [ ]:
!pip install optuna

import optuna

study=optuna.create_study(direction="maximize")
study.optimize(objective,n_trials=25)

In [ ]:
print(study.best_value)
print(study.best_params)

In [ ]:
class myNN3(nn.Module):
  def __init__(self,input_dim, h1_dim, h2_dim, output_dim):
    super().__init__()
    self.linear=nn.Sequential(
        nn.Linear(input_dim,h1_dim),
        nn.BatchNorm1d(h1_dim), # Added Batch Normalization
        nn.ReLU(),
        nn.Dropout(p=0.3),
        nn.Linear(h1_dim,h2_dim),
        nn.BatchNorm1d(h2_dim), # Added Batch Normalization
        nn.ReLU(),
        nn.Dropout(p=0.3),
        nn.Linear(h2_dim,output_dim)
    )
    self.criterion = nn.CrossEntropyLoss()
    self.optimizer = optim.SGD(self.parameters(),lr=0.1,weight_decay=0.0001)

  def forward(self, x):
    return self.linear(x)

  def loss(self,y_pred,y):
    return self.criterion(y_pred,y)


In [ ]:
apun=myNN3(784,128,64,10)
apun=apun.to(device)


In [ ]:
lr=0.1
epochs=200

for i in range(epochs):
  apun.train()
  for batch_feature,batch_label in train_loader:
    batch_feature = batch_feature.to(device)
    batch_label = batch_label.to(device)


    y_pred=apun(batch_feature)
    loss=apun.loss(y_pred,batch_label)

    apun.optimizer.zero_grad()
    loss.backward()
    apun.optimizer.step()

  if i%10==0 :  print(f"epoch: {i}  , loss: {loss*100:.4}%")


In [ ]:
apun.eval()
accuracy=[]
#this is for fashion mnist dataset and output has 10 classes.

with torch.no_grad():
  for batch_feature,batch_label in test_loader:

    batch_feature = batch_feature.to(device, non_blocking=True)
    batch_label = batch_label.to(device, non_blocking=True)
    y_pred=apun.forward(batch_feature)
    y_pred=torch.argmax(y_pred,dim=1)
    accuracy.append((y_pred==batch_label).float().mean().item())

overall_accuracy=sum(accuracy)/len(accuracy)
print(f"overall accuracy: {overall_accuracy}")
