<a href="https://colab.research.google.com/github/SarthakGohil/Pytorch-Exploring/blob/main/pytorch_(6_10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  #6


In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
X.shape

(10, 2)

In [5]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [7]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
from torch.utils.data import Dataset,DataLoader

In [9]:
class myNN2(Dataset):
  def __init__(self,features,lables):
    super().__init__()
    self.features=features
    self.lables=lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx], self.lables[idx]

In [10]:
dataset=myNN2(X,y)

In [11]:
dataset[3]

(tensor([-0.7206, -0.9606]), tensor(0))

In [12]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=1)

In [13]:
for batch_features,batch_loaders in dataloader:
  print(batch_features)
  print(batch_loaders)
  print("-"*50)

tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.5872, -1.9717]])
tensor([0, 0])
--------------------------------------------------
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------


In [14]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler

In [15]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
519     917080         B        12.75         16.70           82.51   
213  881094802         M        17.42         25.56          114.50   
352     899987         M        25.73         17.46          174.20   
421     906564         B        14.69         13.98           98.22   
441     909445         M        17.27         25.42          112.40   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
519      493.8          0.11250            0.1117          0.0388   
213      948.0          0.10060            0.1146          0.1682   
352     2010.0          0.11490            0.2363          0.3368   
421      656.1          0.10310            0.1836          0.1450   
441      928.8          0.08331            0.1109          0.1204   

     concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
519              0.02995  ...          21.74            93.63       624.1   
213              0.06597  ...          28.07           120.40      1021.0   
352              0.19130  ...          23.58           229.30      3234.0   
421              0.06300  ...          18.34           114.10       809.2   
441              0.05736  ...          35.46           132.80      1284.0   

     smoothness_worst  compactness_worst  concavity_worst  \
519            0.1475             0.1979           0.1423   
213            0.1243             0.1793           0.2803   
352            0.1530             0.5937           0.6451   
421            0.1312             0.3635           0.3219   
441            0.1436             0.4122           0.5036   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
519               0.08045          0.3071                  0.08557   
213               0.10990          0.1603                  0.06818   
352               0.27560          0.3690                  0.08815   
421               0.11080          0.2827                  0.09208   
441               0.17390          0.2500                  0.07944   

     Unnamed: 32  
519          NaN  
213          NaN  
352          NaN  
421          NaN  
441          NaN  

[5 rows x 33 columns]

In [16]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [17]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']

In [18]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)

In [19]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [20]:
from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

y_train=LE.fit_transform(y_train)
y_test=LE.transform(y_test)

In [21]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

In [22]:
from torch.utils.data import Dataset,DataLoader,TensorDataset

In [23]:
class for_ds(Dataset):
  def __init__(self,features,labels):
    super().__init__()
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [24]:
train_ds=for_ds(X_train_tensor,y_train_tensor)
test_ds=for_ds(X_test_tensor,y_test_tensor)

In [25]:
train_loader=DataLoader(train_ds,batch_size=32,shuffle=True)
test_loader=DataLoader(test_ds,batch_size=32,shuffle=True)

In [26]:
import torch.nn as nn
import torch.optim as optim

In [27]:
class myNN2(nn.Module):
  def __init__(self,l1_features):
    super().__init__()
    self.linear=nn.Sequential(
        nn.Linear(l1_features,1)
    )
    self.criterian=nn.BCEWithLogitsLoss()
    self.optimizer=optim.SGD(self.parameters(),lr=0.1)

  def forward(self,x):
    return self.linear(x)

  def loss(self,y_pred,y):
    return self.criterian(y_pred,y)

In [28]:
apun=myNN2(X_train_tensor.shape[1])

In [29]:
lr=0.1
epochs=10

for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:

    y_pred=apun(batch_features)
    loss=apun.loss(y_pred,batch_labels.view(-1,1))
    apun.optimizer.zero_grad()
    loss.backward()
    apun.optimizer.step()

  print(f"epoch: {epoch}   loss:{loss}")


epoch: 0   loss:0.07650584727525711
epoch: 1   loss:0.08624409884214401
epoch: 2   loss:0.12707605957984924
epoch: 3   loss:0.11627333611249924
epoch: 4   loss:0.09030918031930923
epoch: 5   loss:0.046896159648895264
epoch: 6   loss:0.027763601392507553
epoch: 7   loss:0.02425762638449669
epoch: 8   loss:0.0797184556722641
epoch: 9   loss:0.10441520065069199


In [30]:
apun.eval()
accuracy=[]

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred=apun(batch_features)
    y_pred=(y_pred>0.8).float()
    accuracy.append((y_pred.view(-1)==batch_labels).float().mean().item())

overall_accuracy=sum(accuracy)/len(accuracy)
print(f"overall accuracy: {overall_accuracy}")

overall accuracy: 0.984375


#     #7

In [31]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split as tts

In [57]:

torch.manual_seed(42)


In [58]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"using device : {device}")


using device : cuda


In [59]:
df=pd.read_csv("/content/fashion-mnist_train.csv")
df.head()


label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [60]:
X=df.drop(columns='label').values
y=df['label'].values
X=X/255.0
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)


In [61]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)


In [62]:
class myMNIST(Dataset):
  def __init__(self,features,labels):
    super().__init__()
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


In [63]:
train_ds=myMNIST(X_train_tensor,y_train_tensor)
test_ds=myMNIST(X_test_tensor,y_test_tensor)


In [64]:
# train_loader = DataLoader(train_ds,batch_size=128,shuffle=True)
# test_loader = DataLoader(test_ds,batch_size=128,shuffle=True)


In [65]:
class MyNN3(nn.Module):
  def __init__(self,input_dim, output_dim,num_hidden_layer,neuron_per_layer,weight_decay,optim_name,lr, dropout_rate):
    super().__init__()
    linear=[]

    for i in range(num_hidden_layer):
      if i==0:
        linear.append(nn.Linear(input_dim,neuron_per_layer))
      else: linear.append(nn.Linear(neuron_per_layer,neuron_per_layer))
      linear.append(nn.BatchNorm1d(neuron_per_layer))
      linear.append(nn.ReLU())
      linear.append(nn.Dropout(p=dropout_rate))
    linear.append(nn.Linear(neuron_per_layer,output_dim))

    self.model=nn.Sequential(*linear)
    self.criterion = nn.CrossEntropyLoss()

    if(optim_name=="Adam"):
      self.optimizer = optim.Adam(self.parameters(),lr=lr,weight_decay=weight_decay)
    elif (optim_name=="SGD"):
      self.optimizer = optim.SGD(self.parameters(),lr=lr,weight_decay=weight_decay)
    elif (optim_name=="RMSprop"):
      self.optimizer = optim.RMSprop(self.parameters(),lr=lr,weight_decay=weight_decay)

  def forward(self,x):
    return self.model(x)

  def loss(self,y_pred,y):
    return self.criterion(y_pred,y)

In [66]:
def objective(trial):
  num_hiden_layer=trial.suggest_int("num_hiden_layer",1,8)
  num_neuron_per_layer=trial.suggest_int("num_neuron_per_layer",8,128,step=8)
  epochs=trial.suggest_int("epochs",10,50,step=5)
  lr=trial.suggest_float("lr",1e-5,1e-1,log=True)
  dropout_rate=trial.suggest_float("dropout_rate",0.1,0.5,step=0.1) # Corrected typo from 'dropoout_rate'
  batch_size=trial.suggest_categorical("batch_size",[32,64,128])
  optim_name=trial.suggest_categorical("optimizer",["SGD","Adam","RMSprop"])
  weight_decay=trial.suggest_float("weight_decay",1e-5,1e-1,log=True)


  train_loader = DataLoader(train_ds,batch_size=batch_size,shuffle=True)
  test_loader = DataLoader(test_ds,batch_size=batch_size,shuffle=True)

  input_dim=784
  output_dim=10

  model=MyNN3(input_dim,output_dim,num_hiden_layer,num_neuron_per_layer,weight_decay,optim_name,lr, dropout_rate)
  model=model.to(device)

  for i in range(epochs):
    model.train()
    for batch_feature,batch_label in train_loader:
      batch_feature = batch_feature.to(device)
      batch_label = batch_label.to(device)


      y_pred=model(batch_feature)
      loss=model.loss(y_pred,batch_label)

      model.optimizer.zero_grad()
      loss.backward()
      model.optimizer.step()

    model.eval()
    accuracy=[]
    #this is for fashion mnist dataset and output has 10 classes.

    with torch.no_grad():
      for batch_feature,batch_label in test_loader:

        batch_feature = batch_feature.to(device, non_blocking=True)
        batch_label = batch_label.to(device, non_blocking=True)
        y_pred=model.forward(batch_feature)
        y_pred=torch.argmax(y_pred,dim=1)
        accuracy.append((y_pred==batch_label).float().mean().item())

    overall_accuracy=sum(accuracy)/len(accuracy)
    return overall_accuracy

In [67]:
!pip install optuna

import optuna

study=optuna.create_study(direction="maximize")
study.optimize(objective,n_trials=25)

[I 2026-02-10 11:57:47,456] A new study created in memory with name: no-name-4906e086-e51a-467f-8642-9bce3800f088
[I 2026-02-10 11:57:53,394] Trial 0 finished with value: 0.7029166666666666 and parameters: {'num_hiden_layer': 5, 'num_neuron_per_layer': 120, 'epochs': 30, 'lr': 0.0038213184033054487, 'dropout_rate': 0.4, 'batch_size': 32, 'optimizer': 'SGD', 'weight_decay': 0.0007144943793661702}. Best is trial 0 with value: 0.7029166666666666.
[I 2026-02-10 11:57:54,866] Trial 1 finished with value: 0.7601673317716476 and parameters: {'num_hiden_layer': 3, 'num_neuron_per_layer': 48, 'epochs': 50, 'lr': 0.00010284863349165994, 'dropout_rate': 0.2, 'batch_size': 128, 'optimizer': 'Adam', 'weight_decay': 0.012508462656487411}. Best is trial 1 with value: 0.7601673317716476.
[I 2026-02-10 11:57:59,990] Trial 2 finished with value: 0.8385 and parameters: {'num_hiden_layer': 4, 'num_neuron_per_layer': 120, 'epochs': 30, 'lr': 8.93951664911105e-05, 'dropout_rate': 0.2, 'batch_size': 32, 'opt

In [68]:
print(study.best_value)
print(study.best_params)

0.8385
{'num_hiden_layer': 4, 'num_neuron_per_layer': 120, 'epochs': 30, 'lr': 8.93951664911105e-05, 'dropout_rate': 0.2, 'batch_size': 32, 'optimizer': 'RMSprop', 'weight_decay': 0.04539906267452595}


In [69]:
study.best_params['num_hiden_layer']

4

In [87]:
class myNN3(nn.Module):
  def __init__(self,input_dim,n_hidden, h_dim,output_dim):
    super().__init__()
    stack=[]

    for i in range(n_hidden):
      if(i==0):
        stack.append(nn.Linear(input_dim,h_dim))
      else:
        stack.append(nn.Linear(h_dim,h_dim))

      stack.append(nn.BatchNorm1d(h_dim))
      stack.append(nn.ReLU())
      stack.append(nn.Dropout(p=study.best_params['dropout_rate']))

    stack.append(nn.Linear(h_dim,output_dim))
    self.linear=nn.Sequential(*stack)


  def forward(self, x):
    return self.linear(x)


In [88]:
model3=myNN3(784,study.best_params['num_hiden_layer'],study.best_params['num_neuron_per_layer'],10)
model3=model3.to(device)


In [89]:
train_ds=myMNIST(X_train_tensor,y_train_tensor)
test_ds=myMNIST(X_test_tensor,y_test_tensor)


train_loader = DataLoader(train_ds,batch_size=study.best_params['batch_size'],shuffle=True)
test_loader = DataLoader(test_ds,batch_size=study.best_params['batch_size'],shuffle=True)


In [90]:
lr=study.best_params['lr']
epochs=study.best_params['epochs']

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model3.parameters(),lr=study.best_params['lr'],weight_decay=study.best_params['weight_decay'])

model3.train()
for i in range(epochs):
  for batch_feature,batch_label in train_loader:

    batch_feature = batch_feature.to(device)
    batch_label = batch_label.to(device)

    optimizer.zero_grad()

    y_pred=model3(batch_feature)
    loss=criterion(y_pred,batch_label)

    loss.backward()
    optimizer.step()

  if i%10==0 :  print(f"epoch: {i}  , loss: {loss}")


epoch: 0  , loss: 2.271152973175049
epoch: 10  , loss: 1.1822054386138916
epoch: 20  , loss: 1.0239975452423096


In [91]:
model3.eval()
accuracy=[]
#this is for fashion mnist dataset and output has 10 classes.

with torch.no_grad():
  for batch_feature,batch_label in test_loader:

    batch_feature = batch_feature.to(device)
    batch_label = batch_label.to(device)

    y_pred=model3.forward(batch_feature)
    y_pred=torch.argmax(y_pred,dim=1)
    accuracy.append((y_pred==batch_label).float().mean().item())

overall_accuracy=sum(accuracy)/len(accuracy)
print(f"overall accuracy: {overall_accuracy}")


overall accuracy: 0.7940833333333334


#THE END
